runtime: python39

env: standard
instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  # Your environment variables here

automatic_scaling:
  min_idle_instances: automatic  # or a specific number
  max_idle_instances: automatic  # or a specific number
  min_pending_latency: automatic  # or a time duration like '30ms'
  max_pending_latency: automatic  # or a time duration like '100ms'
